name: just_notes
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  gap: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.6
  flutter_native_splash:

  # Model gen
  freezed: ^2.2.1
  json_annotation: ^4.7.0

  #DI
  get_it: ^7.2.0
  injectable: ^1.5.4

  # Network
  dio: ^4.0.6
  retrofit: ^3.3.1
  pretty_dio_logger: ^1.1.1
  internet_connection_checker: ^1.0.0+1

  #Local storage
  sqflite: any
  path_provider: any

  #local_auth:
  local_auth: ^2.1.2

  #state management
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1

  #route
  go_router: 8.0.5

  #firebase
  firebase_core: 2.14.0
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:
  build_runner:
  flutter_gen_runner:
  retrofit_generator: '>=4.0.0 <5.0.0'
  freezed:
  json_serializable:
  flutter_launcher_icons:

# run : flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  background_color: "#000000"
  image_path: "assets/images/note_3d_logo.png"
  min_sdk_android: 16

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: assets/images/note_3d_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
